/*
 * JS for B_HowToUse generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '92583dc2-8eb0-4fef-8a0d-0df05d9907f9';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "D_WritingCultureTetrad",
    "location": "D_WritingCultureTetrad.html"
}, {
    "name": "C_RapTetrad",
    "location": "C_RapTetrad.html"
}, {
    "name": "B_HowToUse",
    "location": "B_HowToUse.html"
}, {
    "name": "A_HomeScreen",
    "location": "A_HomeScreen.html"
}];

$(document).bind('scroll', function() {
    adjustContentHeightWithPadding();
});
$(window).bind(window.orientation ? 'orientationchange' : 'resize', function() {
    adjustContentHeightWithPadding();
});

function B_HowToUse_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'titleLabel': 'B_HowToUse_titleLabel',
        'mobilegrid_52': 'B_HowToUse_mobilegrid_52',
        'mobilegridcell_53': 'B_HowToUse_mobilegridcell_53',
        'mobilelabel_61': 'B_HowToUse_mobilelabel_61',
        'spacer_62': 'B_HowToUse_spacer_62',
        'mobilelabel_60': 'B_HowToUse_mobilelabel_60',
        'spacer_64': 'B_HowToUse_spacer_64',
        'mobilelabel_63': 'B_HowToUse_mobilelabel_63',
        'mobilegridcell_57': 'B_HowToUse_mobilegridcell_57',
        'mobilelabel_65': 'B_HowToUse_mobilelabel_65',
        'mobilelabel_68': 'B_HowToUse_mobilelabel_68',
        'mobilelabel_66': 'B_HowToUse_mobilelabel_66',
        'mobilelabel_69': 'B_HowToUse_mobilelabel_69',
        'mobilegrid_23': 'B_HowToUse_mobilegrid_23',
        'mobilegridcell_24': 'B_HowToUse_mobilegridcell_24',
        'enhanceLabel': 'B_HowToUse_enhanceLabel',
        'mobilegridcell_25': 'B_HowToUse_mobilegridcell_25',
        'mobilelabel_49': 'B_HowToUse_mobilelabel_49',
        'mobilegridcell_26': 'B_HowToUse_mobilegridcell_26',
        'retreiveLabel': 'B_HowToUse_retreiveLabel',
        'mobilegridcell_27': 'B_HowToUse_mobilegridcell_27',
        'obsolesceLabel': 'B_HowToUse_obsolesceLabel',
        'youtube_39': 'B_HowToUse_youtube_39',
        'html_43': 'B_HowToUse_html_43'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        // Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role='footer']").css("bottom", "-36px");
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'B_HowToUse';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var B_HowToUse_onLoad = function() {
            B_HowToUse_elementsExtraJS();

            B_HowToUse_deviceEvents();
            B_HowToUse_windowEvents();
            B_HowToUse_elementsEvents();
        };

    // screen window events


    function B_HowToUse_windowEvents() {

        $('#B_HowToUse').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function B_HowToUse_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function B_HowToUse_elementsExtraJS() {
        // screen (B_HowToUse) extra code

        /* EnhancePopup */
        $("#B_HowToUse_EnhancePopup").popup("option", "positionTo", "window");

        Apperyio.registerYoutubeComponent("B_HowToUse_youtube_39");

        /* RetrievePopup */
        $("#B_HowToUse_RetrievePopup").popup("option", "positionTo", "window");

    };

    // screen elements handler


    function B_HowToUse_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

    };

    $(document).off("pagebeforeshow", "#B_HowToUse").on("pagebeforeshow", "#B_HowToUse", function(event, ui) {
        Apperyio.CurrentScreen = "B_HowToUse";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    B_HowToUse_onLoad();
};

$(document).off("pagecreate", "#B_HowToUse").on("pagecreate", "#B_HowToUse", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    B_HowToUse_js();
});