/*
 * JS for D_WritingCultureTetrad generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '92583dc2-8eb0-4fef-8a0d-0df05d9907f9';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "D_WritingCultureTetrad",
    "location": "D_WritingCultureTetrad.html"
}, {
    "name": "C_RapTetrad",
    "location": "C_RapTetrad.html"
}, {
    "name": "B_HowToUse",
    "location": "B_HowToUse.html"
}, {
    "name": "A_HomeScreen",
    "location": "A_HomeScreen.html"
}];

$(document).bind('scroll', function() {
    adjustContentHeightWithPadding();
});
$(window).bind(window.orientation ? 'orientationchange' : 'resize', function() {
    adjustContentHeightWithPadding();
});

function D_WritingCultureTetrad_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'titleLabel': 'D_WritingCultureTetrad_titleLabel',
        'mobilegrid_23': 'D_WritingCultureTetrad_mobilegrid_23',
        'mobilegridcell_24': 'D_WritingCultureTetrad_mobilegridcell_24',
        'enhanceLabel': 'D_WritingCultureTetrad_enhanceLabel',
        'spacer_45': 'D_WritingCultureTetrad_spacer_45',
        'enhanceDefLabel': 'D_WritingCultureTetrad_enhanceDefLabel',
        'mobilegridcell_25': 'D_WritingCultureTetrad_mobilegridcell_25',
        'mobilegridcell_30': 'D_WritingCultureTetrad_mobilegridcell_30',
        'mobilelabel_49': 'D_WritingCultureTetrad_mobilelabel_49',
        'spacer_50': 'D_WritingCultureTetrad_spacer_50',
        'mobilelabel_51': 'D_WritingCultureTetrad_mobilelabel_51',
        'mobilegridcell_26': 'D_WritingCultureTetrad_mobilegridcell_26',
        'mobilegridcell_27': 'D_WritingCultureTetrad_mobilegridcell_27',
        'mobilegridcell_31': 'D_WritingCultureTetrad_mobilegridcell_31',
        'mobilegridcell_28': 'D_WritingCultureTetrad_mobilegridcell_28',
        'retrieveLabel': 'D_WritingCultureTetrad_retrieveLabel',
        'spacer_46': 'D_WritingCultureTetrad_spacer_46',
        'RetrieveDefLabel': 'D_WritingCultureTetrad_RetrieveDefLabel',
        'mobilegridcell_29': 'D_WritingCultureTetrad_mobilegridcell_29',
        'mobilegridcell_32': 'D_WritingCultureTetrad_mobilegridcell_32',
        'obsolescenceLabel': 'D_WritingCultureTetrad_obsolescenceLabel',
        'spacer_47': 'D_WritingCultureTetrad_spacer_47',
        'obsolescenceDefLabel': 'D_WritingCultureTetrad_obsolescenceDefLabel',
        'youtube_39': 'D_WritingCultureTetrad_youtube_39',
        'html_43': 'D_WritingCultureTetrad_html_43'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        // Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role='footer']").css("bottom", "-36px");
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'D_WritingCultureTetrad';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var D_WritingCultureTetrad_onLoad = function() {
            D_WritingCultureTetrad_elementsExtraJS();

            D_WritingCultureTetrad_deviceEvents();
            D_WritingCultureTetrad_windowEvents();
            D_WritingCultureTetrad_elementsEvents();
        };

    // screen window events


    function D_WritingCultureTetrad_windowEvents() {

        $('#D_WritingCultureTetrad').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function D_WritingCultureTetrad_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function D_WritingCultureTetrad_elementsExtraJS() {
        // screen (D_WritingCultureTetrad) extra code

        /* EnhancePopup */
        $("#D_WritingCultureTetrad_EnhancePopup").popup("option", "positionTo", "window");

        Apperyio.registerYoutubeComponent("D_WritingCultureTetrad_youtube_39");

        /* RetrievePopup */
        $("#D_WritingCultureTetrad_RetrievePopup").popup("option", "positionTo", "window");

    };

    // screen elements handler


    function D_WritingCultureTetrad_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

    };

    $(document).off("pagebeforeshow", "#D_WritingCultureTetrad").on("pagebeforeshow", "#D_WritingCultureTetrad", function(event, ui) {
        Apperyio.CurrentScreen = "D_WritingCultureTetrad";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    D_WritingCultureTetrad_onLoad();
};

$(document).off("pagecreate", "#D_WritingCultureTetrad").on("pagecreate", "#D_WritingCultureTetrad", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    D_WritingCultureTetrad_js();
});